---

- hosts: all
  become: true

  vars_files:
    - ~/.ansible/vault.yml

  vars:
    ansible_become_pass: "{{ sudo_password }}"

  tasks:
    - name: Ensure resolvconf config is in place
      blockinfile:
        path: /etc/resolv.conf
        state: present
        block: |
          nameserver 10.0.1.2
          nameserver 10.0.1.5
          search maclaren.dev
          search gillette.net
      when: inventory_hostname not in groups['azure']
