---

- hosts: all
  become: true

  tasks:
    - name: Ensure required packages are installed
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - resolvconf
        - python

