---
- hosts: lab
  become: true
  serial: 1

  vars_files:
    - ~/.ansible/vault.yml

  vars:
    ansible_become_pass: "{{ sudo_password }}"


  tasks:
    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file

    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when:
        - reboot_required_file.stat.exists == true

    - name: Pause to wait for host to fully come online
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      when:
        - reboot_required_file is changed
