---
- hosts: all
  become: true

  vars_files:
    - ~/.ansible/vault.yml

  vars:
    ansible_become_pass: "{{ sudo_password }}"


  tasks:
    - name: Update cache
      apt:
       update_cache: yes
       cache_valid_time: 86400

    - name: Upgrade all packages on servers
      apt:
        name: "*"
        state: latest

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
