---
- hosts: all 
  become: true

  vars_files:
    - ~/.ansible/vault.yml

  vars:
    ansible_become_pass: "{{ sudo_password }}" 

  tasks:
    - name: Update cache 
      apt:
       update_cache: yes
       cache_valid_time: 86400
         
    - name: Upgrade all packages on servers
      apt: 
        name: "*"
        state: latest
        
    - name: Check if a reboot is required.
      hosts: lab
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file

    - name: Reboot the server (if required).
      hosts: lab
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
